"""empty message

Revision ID: 1320a7c09a1a
Revises: 653ea60a1779
Create Date: 2020-06-17 22:14:58.719484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1320a7c09a1a'
down_revision = '653ea60a1779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('past_performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=True),
    sa.Column('foreign_or_domestic', sa.String(), nullable=True),
    sa.Column('foreign_race', sa.String(), nullable=True),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('track_code', sa.String(), nullable=True),
    sa.Column('race_number', sa.Integer(), nullable=True),
    sa.Column('surface', sa.String(), nullable=True),
    sa.Column('timeform_code', sa.String(), nullable=True),
    sa.Column('inner_track_code', sa.String(), nullable=True),
    sa.Column('distance', sa.DECIMAL(), nullable=True),
    sa.Column('race_class', sa.String(), nullable=True),
    sa.Column('claim_price', sa.DECIMAL(), nullable=True),
    sa.Column('purse', sa.DECIMAL(), nullable=True),
    sa.Column('track_condition', sa.String(), nullable=True),
    sa.Column('sex_restrictions', sa.String(), nullable=True),
    sa.Column('age_restrictions', sa.String(), nullable=True),
    sa.Column('state_bred', sa.String(), nullable=True),
    sa.Column('field_size', sa.Integer(), nullable=True),
    sa.Column('first_fraction', sa.DECIMAL(), nullable=True),
    sa.Column('second_fraction', sa.DECIMAL(), nullable=True),
    sa.Column('third_fraction', sa.DECIMAL(), nullable=True),
    sa.Column('fourth_fraction', sa.DECIMAL(), nullable=True),
    sa.Column('fifth_fraction', sa.DECIMAL(), nullable=True),
    sa.Column('sixth_fraction', sa.DECIMAL(), nullable=True),
    sa.Column('final_time', sa.DECIMAL(), nullable=True),
    sa.Column('first_horse', sa.String(), nullable=True),
    sa.Column('second_horse', sa.String(), nullable=True),
    sa.Column('third_horse', sa.String(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('post_position', sa.Integer(), nullable=True),
    sa.Column('first_call_position', sa.Integer(), nullable=True),
    sa.Column('first_call_lengths_back', sa.DECIMAL(), nullable=True),
    sa.Column('second_call_position', sa.Integer(), nullable=True),
    sa.Column('second_call_lengths_back', sa.DECIMAL(), nullable=True),
    sa.Column('third_call_position', sa.Integer(), nullable=True),
    sa.Column('third_call_lengths_back', sa.DECIMAL(), nullable=True),
    sa.Column('fourth_call_position', sa.Integer(), nullable=True),
    sa.Column('fourth_call_lengths_back', sa.DECIMAL(), nullable=True),
    sa.Column('stretch_call_position', sa.Integer(), nullable=True),
    sa.Column('stretch_call_lengths_back', sa.DECIMAL(), nullable=True),
    sa.Column('final_call_position', sa.Integer(), nullable=True),
    sa.Column('final_call_lengths_back', sa.DECIMAL(), nullable=True),
    sa.Column('beyer_or_foreign_speed', sa.Integer(), nullable=True),
    sa.Column('odds', sa.DECIMAL(), nullable=True),
    sa.Column('odds_position', sa.Integer(), nullable=True),
    sa.Column('claimed_code', sa.String(), nullable=True),
    sa.Column('lasix', sa.String(), nullable=True),
    sa.Column('bute', sa.String(), nullable=True),
    sa.Column('blinkers', sa.String(), nullable=True),
    sa.Column('bandages', sa.String(), nullable=True),
    sa.Column('jockey', sa.String(), nullable=True),
    sa.Column('trainer', sa.String(), nullable=True),
    sa.Column('track_variant', sa.Integer(), nullable=True),
    sa.Column('speed_rating', sa.Integer(), nullable=True),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('horse_id', 'track_code', 'race_date', name='uniq_horse_track_date')
    )
    op.create_index('_horse_track_date', 'past_performances', ['horse_id', 'track_code', 'race_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('_horse_track_date', table_name='past_performances')
    op.drop_table('past_performances')
    # ### end Alembic commands ###
