"""empty message

Revision ID: 3968538d0d4b
Revises: 85e127098eab
Create Date: 2020-07-19 19:16:43.743567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3968538d0d4b'
down_revision = '85e127098eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('blinker_change', sa.String(), nullable=True))
    op.add_column('results', sa.Column('cur_year_earn', sa.DECIMAL(), nullable=True))
    op.add_column('results', sa.Column('cur_year_places', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('cur_year_shows', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('cur_year_starts', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('cur_year_wins', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('distance_earn', sa.DECIMAL(), nullable=True))
    op.add_column('results', sa.Column('distance_places', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('distance_shows', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('distance_starts', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('distance_wins', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('fast_dirt_earn', sa.DECIMAL(), nullable=True))
    op.add_column('results', sa.Column('fast_dirt_places', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('fast_dirt_shows', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('fast_dirt_starts', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('fast_dirt_wins', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('jockey_meet_earn', sa.DECIMAL(), nullable=True))
    op.add_column('results', sa.Column('jockey_meet_places', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('jockey_meet_shows', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('jockey_meet_starts', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('jockey_meet_wins', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('jockey_ytd_earn', sa.DECIMAL(), nullable=True))
    op.add_column('results', sa.Column('jockey_ytd_places', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('jockey_ytd_shows', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('jockey_ytd_starts', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('jockey_ytd_wins', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('prior_year_earn', sa.DECIMAL(), nullable=True))
    op.add_column('results', sa.Column('prior_year_places', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('prior_year_shows', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('prior_year_starts', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('prior_year_wins', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('track_earn', sa.DECIMAL(), nullable=True))
    op.add_column('results', sa.Column('track_places', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('track_shows', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('track_starts', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('track_wins', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('trainer_meet_earn', sa.DECIMAL(), nullable=True))
    op.add_column('results', sa.Column('trainer_meet_places', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('trainer_meet_shows', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('trainer_meet_starts', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('trainer_meet_wins', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('trainer_ytd_earn', sa.DECIMAL(), nullable=True))
    op.add_column('results', sa.Column('trainer_ytd_places', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('trainer_ytd_shows', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('trainer_ytd_starts', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('trainer_ytd_wins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'trainer_ytd_wins')
    op.drop_column('results', 'trainer_ytd_starts')
    op.drop_column('results', 'trainer_ytd_shows')
    op.drop_column('results', 'trainer_ytd_places')
    op.drop_column('results', 'trainer_ytd_earn')
    op.drop_column('results', 'trainer_meet_wins')
    op.drop_column('results', 'trainer_meet_starts')
    op.drop_column('results', 'trainer_meet_shows')
    op.drop_column('results', 'trainer_meet_places')
    op.drop_column('results', 'trainer_meet_earn')
    op.drop_column('results', 'track_wins')
    op.drop_column('results', 'track_starts')
    op.drop_column('results', 'track_shows')
    op.drop_column('results', 'track_places')
    op.drop_column('results', 'track_earn')
    op.drop_column('results', 'prior_year_wins')
    op.drop_column('results', 'prior_year_starts')
    op.drop_column('results', 'prior_year_shows')
    op.drop_column('results', 'prior_year_places')
    op.drop_column('results', 'prior_year_earn')
    op.drop_column('results', 'jockey_ytd_wins')
    op.drop_column('results', 'jockey_ytd_starts')
    op.drop_column('results', 'jockey_ytd_shows')
    op.drop_column('results', 'jockey_ytd_places')
    op.drop_column('results', 'jockey_ytd_earn')
    op.drop_column('results', 'jockey_meet_wins')
    op.drop_column('results', 'jockey_meet_starts')
    op.drop_column('results', 'jockey_meet_shows')
    op.drop_column('results', 'jockey_meet_places')
    op.drop_column('results', 'jockey_meet_earn')
    op.drop_column('results', 'fast_dirt_wins')
    op.drop_column('results', 'fast_dirt_starts')
    op.drop_column('results', 'fast_dirt_shows')
    op.drop_column('results', 'fast_dirt_places')
    op.drop_column('results', 'fast_dirt_earn')
    op.drop_column('results', 'distance_wins')
    op.drop_column('results', 'distance_starts')
    op.drop_column('results', 'distance_shows')
    op.drop_column('results', 'distance_places')
    op.drop_column('results', 'distance_earn')
    op.drop_column('results', 'cur_year_wins')
    op.drop_column('results', 'cur_year_starts')
    op.drop_column('results', 'cur_year_shows')
    op.drop_column('results', 'cur_year_places')
    op.drop_column('results', 'cur_year_earn')
    op.drop_column('results', 'blinker_change')
    # ### end Alembic commands ###
