"""empty message

Revision ID: 4ee388a4cf87
Revises: 1320a7c09a1a
Create Date: 2020-06-17 23:11:50.189609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee388a4cf87'
down_revision = '1320a7c09a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('past_performances', sa.Column('horse_name', sa.String(), nullable=True))
    op.add_column('past_performances', sa.Column('today_date', sa.Date(), nullable=True))
    op.add_column('past_performances', sa.Column('today_race_number', sa.Integer(), nullable=True))
    op.add_column('past_performances', sa.Column('today_track', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('past_performances', 'today_track')
    op.drop_column('past_performances', 'today_race_number')
    op.drop_column('past_performances', 'today_date')
    op.drop_column('past_performances', 'horse_name')
    # ### end Alembic commands ###
