"""empty message

Revision ID: 653ea60a1779
Revises: 
Create Date: 2020-05-02 16:11:15.741394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653ea60a1779'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('sex', sa.String(), nullable=True),
                    sa.Column('year_born', sa.Integer(), nullable=True),
                    sa.Column('month_born', sa.Integer(), nullable=True),
                    sa.Column('location_born', sa.String(), nullable=True),
                    sa.Column('breeder', sa.String(), nullable=True),
                    sa.Column('color', sa.String(), nullable=True),
                    sa.Column('sire', sa.String(), nullable=True),
                    sa.Column('sire_sire', sa.String(), nullable=True),
                    sa.Column('dam', sa.String(), nullable=True),
                    sa.Column('dam_sire', sa.String(), nullable=True),
                    sa.Column('sale_location', sa.String(), nullable=True),
                    sa.Column('sale_year', sa.Integer(), nullable=True),
                    sa.Column('sale_price', sa.DECIMAL(), nullable=True),
                    sa.Column('stud_fee', sa.DECIMAL(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name', name='uniq_horse_name')
                    )
    op.create_table('jockeys',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('full_name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('full_name', name='uniq_jockey')
                    )
    op.create_table('owners',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('full_name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('full_name', name='uniq_owner')
                    )
    op.create_table('tracks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('code', sa.String(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('state', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code', name='uniq_code')
                    )
    op.create_index('code_index', 'tracks', ['code'], unique=False)
    op.create_table('trainers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('full_name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('full_name', name='uniq_trainer')
                    )
    op.create_table('courses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('track_id', sa.Integer(), nullable=True),
                    sa.Column('track_code', sa.String(), nullable=True),
                    sa.Column('distance', sa.DECIMAL(), nullable=True),
                    sa.Column('surface', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('track_code', 'distance',
                                        'surface', name='uniq_course')
                    )
    op.create_index('distance_index', 'courses', ['distance'], unique=False)
    op.create_index('track_code_index', 'courses',
                    ['track_code'], unique=False)
    op.create_table('races',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('track_id', sa.Integer(), nullable=True),
                    sa.Column('course_id', sa.Integer(), nullable=True),
                    sa.Column('date', sa.Date(), nullable=True),
                    sa.Column('race_number', sa.Integer(), nullable=True),
                    sa.Column('is_state_bred', sa.String(), nullable=True),
                    sa.Column('sex_restrictions', sa.String(), nullable=True),
                    sa.Column('age_restrictions', sa.String(), nullable=True),
                    sa.Column('classification', sa.String(), nullable=True),
                    sa.Column('purse', sa.DECIMAL(), nullable=True),
                    sa.Column('claim_price', sa.DECIMAL(), nullable=True),
                    sa.Column('grade', sa.Integer(), nullable=True),
                    sa.Column('day_of_week', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
                    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('track_id', 'date', 'race_number',
                                        name='uniq_track_date_rnum')
                    )
    op.create_index('date_index', 'races', ['date'], unique=False)
    op.create_table('results',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('race_id', sa.Integer(), nullable=True),
                    sa.Column('horse_id', sa.Integer(), nullable=True),
                    sa.Column('trainer_id', sa.Integer(), nullable=True),
                    sa.Column('jockey_id', sa.Integer(), nullable=True),
                    sa.Column('owner_id', sa.Integer(), nullable=True),
                    sa.Column('last_raced', sa.Date(), nullable=True),
                    sa.Column('lasix', sa.String(), nullable=True),
                    sa.Column('claiming_price', sa.DECIMAL(), nullable=True),
                    sa.Column('lifetime_earn', sa.DECIMAL(), nullable=True),
                    sa.Column('lifetime_starts', sa.Integer(), nullable=True),
                    sa.Column('lifetime_wins', sa.Integer(), nullable=True),
                    sa.Column('lifetime_places', sa.Integer(), nullable=True),
                    sa.Column('lifetime_shows', sa.Integer(), nullable=True),
                    sa.Column('turf_earn', sa.DECIMAL(), nullable=True),
                    sa.Column('turf_starts', sa.Integer(), nullable=True),
                    sa.Column('turf_wins', sa.Integer(), nullable=True),
                    sa.Column('turf_places', sa.Integer(), nullable=True),
                    sa.Column('turf_shows', sa.Integer(), nullable=True),
                    sa.Column('odds', sa.Integer(), nullable=True),
                    sa.Column('post_position', sa.Integer(), nullable=True),
                    sa.Column('program_number', sa.String(), nullable=True),
                    sa.Column('start_position', sa.Integer(), nullable=True),
                    sa.Column('first_call_position',
                              sa.Integer(), nullable=True),
                    sa.Column('second_call_position',
                              sa.Integer(), nullable=True),
                    sa.Column('third_call_position',
                              sa.Integer(), nullable=True),
                    sa.Column('fourth_call_position',
                              sa.Integer(), nullable=True),
                    sa.Column('fifth_call_position',
                              sa.Integer(), nullable=True),
                    sa.Column('final_position', sa.Integer(), nullable=True),
                    sa.Column('first_call_lengths_ahead',
                              sa.DECIMAL(), nullable=True),
                    sa.Column('second_call_lengths_ahead',
                              sa.DECIMAL(), nullable=True),
                    sa.Column('third_call_lengths_ahead',
                              sa.DECIMAL(), nullable=True),
                    sa.Column('fourth_call_lengths_ahead',
                              sa.DECIMAL(), nullable=True),
                    sa.Column('fifth_call_lengths_ahead',
                              sa.DECIMAL(), nullable=True),
                    sa.Column('final_lengths_ahead',
                              sa.DECIMAL(), nullable=True),
                    sa.Column('first_call_lengths_behind',
                              sa.DECIMAL(), nullable=True),
                    sa.Column('second_call_lengths_behind',
                              sa.DECIMAL(), nullable=True),
                    sa.Column('third_call_lengths_behind',
                              sa.DECIMAL(), nullable=True),
                    sa.Column('fourth_call_lengths_behind',
                              sa.DECIMAL(), nullable=True),
                    sa.Column('fifth_call_lengths_behind',
                              sa.DECIMAL(), nullable=True),
                    sa.Column('final_lengths_behind',
                              sa.DECIMAL(), nullable=True),
                    sa.Column('win_pay', sa.DECIMAL(), nullable=True),
                    sa.Column('place_pay', sa.DECIMAL(), nullable=True),
                    sa.Column('show_pay', sa.DECIMAL(), nullable=True),
                    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
                    sa.ForeignKeyConstraint(['jockey_id'], ['jockeys.id'], ),
                    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
                    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
                    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint(
                        'horse_id', 'race_id', name='uniq_result')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_index('date_index', table_name='races')
    op.drop_table('races')
    op.drop_index('track_code_index', table_name='courses')
    op.drop_index('distance_index', table_name='courses')
    op.drop_table('courses')
    op.drop_table('trainers')
    op.drop_index('code_index', table_name='tracks')
    op.drop_table('tracks')
    op.drop_table('owners')
    op.drop_table('jockeys')
    op.drop_table('horses')
    # ### end Alembic commands ###
