"""empty message

Revision ID: 660ef9f72870
Revises: 908476d0f9b7
Create Date: 2020-08-17 23:03:34.562076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660ef9f72870'
down_revision = '908476d0f9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column(
        'predicted_closer_percent', sa.DECIMAL(), nullable=True))
    op.add_column('races', sa.Column(
        'predicted_pacer_percent', sa.DECIMAL(), nullable=True))
    op.add_column('races', sa.Column(
        'predicted_wire_percent', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'predicted_pacer_percent')
    op.drop_column('races', 'predicted_closer_percent')
    op.drop_column('races', 'predicted_wire_percent')
    # ### end Alembic commands ###
