"""empty message

Revision ID: d6de2ddebb45
Revises: 660ef9f72870
Create Date: 2021-02-05 22:40:30.927607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6de2ddebb45'
down_revision = '660ef9f72870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('post_time', sa.String(), nullable=True))
    op.add_column('races', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'state')
    op.drop_column('races', 'post_time')
    # ### end Alembic commands ###
